"""another fix

Revision ID: 314d107f855f
Revises: b9b3fd70dd5e
Create Date: 2025-12-07 06:45:59.876937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314d107f855f'
down_revision = 'b9b3fd70dd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')

    # ### end Alembic commands ###
