"""add is_active, author

Revision ID: 5f82993cadb4
Revises: 55b87d4904e6
Create Date: 2025-12-04 01:43:51.559430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f82993cadb4'
down_revision = '55b87d4904e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('category', sa.Enum('news', 'publication', 'tech', 'other', name='post_category'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
